### ISSUE TITLE
scrollbar not visible on large resolution

### ISSUE THREAD

**Issue by boing86** [yanncam/KodiWebPortal#20]
I discovered something that "only" appears on large monitors.

If the variable DEFAULT_ENTRIES_DISPLAY = 16 and the monitor 2560x1600 there is no scrollbar .--> You can not view any more movies.

You have to make the browser smaller so that a scrollbar is visible, then you can load more movies.

The easiest way to solve this is to increase DEFAULT_ENTRIES_DISPLAY.

**Comment by yanncam** [comment]
Hello,

Ok, I think the reason of this bug is the next one:

- By default, `DEFAULT_ENTRIES_DISPLAY` is set to 16
- With a wide screen with high resolution (2560x1600), 16 entries printed by default isn't enough to display the scrollbar of the browser's window. The behaviour can be simulated by un-zooming in firefox or chrome the main page of KWP.
- The loading mecanism of the next 16 entries is triggered on the event `$(window).scroll()` in the `script.js` file
- So if your screen is too wide and no-scroll is displayed at the first time, there is no chance to trigger this event => the bug

To mitigate this behaviour, you can:
- Adjust the `DEFAULT_ENTRIES_DISPLAY` value to a bigger one (20, 32 as example, depending of your screensize) to force an initial scrollbar on the window
- Or I can add a "button" in the bttom-right-corner with an event "onclick" to "load more result" (same code as the one trigger by the `$(window).scroll()`)

Sincerely,

**Comment by boing86** [comment]
Hello

For me it is ok if you increase the variable DEFAULT_ENTRIES_DISPLAY.
Just wanted to share it.

Greeting
