### ISSUE TITLE
Installation nginx/php/mysql on debian

### ISSUE THREAD

**Issue by 1985kasper** [yanncam/KodiWebPortal#21]
Hi,

A co-worker pointed me out to this project and i wanted to try it out on my debian 9 server running nginx (no apache installed) with mariadb (mysql  Ver 15.1 Distrib 10.1.26-MariaDB)

Initially it seems to work, the movie titles and some of the descriptions are shown. However most of the posters (except for one) are missing and so is most of the descriptions (plot) for the movies and tv shows. Some testing and digging showed that it makes a difference if there is local .nfo and other content in the same directory as the movie file. Because i use Radarr almost all directories contain posters and other information already.

Another issue running into is that downloading any file is not possible. It will just download a bogus file of 3 bytes with the title and extension of the actual file. 

Could you provide any insight into how to get this working with nginx?

Rgds,

Kasper

**Comment by yanncam** [comment]
Hello @1985kasper,

I haven't tried KWP on Nginx, but there is (theoricaly) no problem of compliance.

Posters of movies are retrieved from the MySQL/Maria database. If your movie's folder contains a *.nfo and fanart/poster, KWP doesn't tried to load them, these files are ignored by the web application.

Please check your database content to see if there are fanart/poster URL (in XML format) in movie's content. If yes, your browser seems to block external images loading.
To troubleshoot, can you display the browser console after loading KWP page ? (F12 then "console" in Firefox or Chrome).

I think there is a HTTPS or HSTS or CSP header in your Nginx to prevent loading external images.

Finally, for the downloading feature, yes, it's normal that it doesn't work on Nginx because the feature relies on the "Apache mod_xsendfile". So you have to enable a similar feature on Nginx.

Please check : https://www.nginx.com/resources/wiki/start/topics/examples/xsendfile/

Sincerely,

**Comment by yanncam** [comment]
Hello,

I close this issue, consider it as resolved without feedback.

Sincerely,
