### ISSUE TITLE
Problem with hashed password

### ISSUE THREAD

**Issue by JayRabas** [yanncam/KodiWebPortal#24]
I successfully installed KodiWebPortal with Debian, but I found a (simple) problem which took me a long time to resolve: When using internal authentication, if the hashed password contains a letter after a '$', it doesn't work:
This work:
"$2y$10$471cELEUsyQJqaDyJBuXzOoBCEWfZwvMBtGsGLOQPwNH8DLInzJlq"
This doesn't work:
"$2y$10$DE4pIntIpyaC8TW.ZkQBPuuloY3IUQwwpHk5xzryeCUrsCW3/Zek6"
whereas it is the same password. I suppose PHP convert $DE4pIntIpyaC8TW to a variable.

**Comment by yanncam** [comment]
Hello,

You're right, there is a little mistake in this code.
The BCrypt's hashes need to be surrounded by **simple-quote** like `'` and not **double-quote** like `"` to prevent the `$` symbol to be interpreted as a PHP variable prefix.

So, please change in the `config.php` file the definition of hash :

* from :

```
"$2y$10$DE4pIntIpyaC8TW.ZkQBPuuloY3IUQwwpHk5xzryeCUrsCW3/Zek6"
```

* to :

```
'$2y$10$DE4pIntIpyaC8TW.ZkQBPuuloY3IUQwwpHk5xzryeCUrsCW3/Zek6'
```

* or you can escape all `$` signs with a blackslash like `\$` and keep the **double-quote** `"`.

FYI, it works with the default hash `$2y$10$471cELEUsyQJqaDyJBuXzOoBCEWfZwvMBtGsGLOQPwNH8DLInzJlq` because each characters following each `$` sign is numeric, si it can't be a valid PHP variable name.

I'll update the `config.php` file.

Sincerely,

**Comment by yanncam** [comment]
Commit here : https://github.com/yanncam/KodiWebPortal/commit/aedf4c1582db659ee630476ddfee12bd9e4ae8a6

**Comment by JayRabas** [comment]
Thank you!
