### ISSUE TITLE
Empty files

### ISSUE THREAD

**Issue by oalbaf** [yanncam/KodiWebPortal#3]
Hi,

My system is a DSM 6.0.

I followed the instructions, but I think I have a problem with the X-send-file Apache module configuration. Should this module be installed separately? There was no mod_xsendfile.conf-user file and I created it manually. I have followed all the steps in the manual and I think something is missing.

Everything seems to work fine, but when downloading a movie the file only has 3 bytes.

What could be the problem? Thank you!

**Comment by boing86** [comment]
I use Apache2.4.
Webstation / General Settings / HTTp Backend Server -> Apache 2.4

Then there is this file with me.
/volume1/@appstore/Apache2.4/usr/local/etc/apache24/conf/extra/mod_xsendfile.conf

**Comment by oalbaf** [comment]
I use Apache 2.4 too

thanks for the clue! My path is:
/ volume1/@appstore/Apache2.4/usr/local/etc/apache24/conf/extra/

But when I edit mod_xsendfile.conf... Apache 2.4 then turn off and don't want start!! Help!!

Thank you!!

**Comment by oalbaf** [comment]
Solved!!

Solved!!

In mod_xsendfile.conf erase other paths in XSendFilesPath and only add your library path.

Thank you boing86 and yanncam!!

**Comment by yanncam** [comment]
Hello oalbaf, boing86,

Thank you for this issue and your solution.
Since several weeks / months, Synology had upgraded their web-server packages. Now, through the Synology store, it's possible to choose between **Apache 2.2** or **Apache 2.4**.
So there is now different paths to the **mod_xsendfile.conf** file in the Synology file system.

From your issue, I've updated the README.md of this GitHub's project to include new paths that you provide.

Plus, for the future, I have indicated a generic SSH command to find the right mod_xsendfile.conf in the filesystem :

```
find / -name "*xsendfile*conf*"
```

Thank you again, I will close this issue.

Sincerely, and have fun with KodiWebPortal :) !

ycam

**Comment by j1pe** [comment]
Hi,
I have the same problem, so rather than opening a new issue, I'll take this one again.

I'm with a syno NAS DSM 6.2,
The site works fine, the link to the database is correct however, when I download a file, it's 3 bytes.

Here is my file: 

> /volume1/@appstore/Apache2.4/usr/local/etc/apache24/conf/extra/mod_xsendfile.conf

```
LoadModule xsendfile_module modules/mod_xsendfile.so

XSendFile on
XSendFilePath /volume1/download
SetEnv MOD_X_SENDFILE_ENABLED yes
```

I rebooted the NAS and the Web station package several times.

Thanks in advance for the help and congratulations for the good job.
